config/routes.rb
Rails.application.routes.draw do

  resources :tipos
  resources :linhas
  resources :tamanhos
  resources :cores

  resources :produtos do
    get :lucro, on: :collection
    resources :etiquetas
  end

  resources :vendas do
    resources :itens, controller: 'vendas/itens'
    resources :trocas, controller: 'vendas/trocas'
    resources :registros, controller: 'vendas/registros'
    get 'mensal', on: :collection
  end

  resources :compras do
    resources :itens, controller: 'compras/itens'
    resources :registros, controller: 'compras/registros'
    resources :trocas, controller: 'compras/trocas'
  end

  resources :ajustes do
    resources :itens, controller: 'ajustes/itens'
  end

  resources :estoque

  get  'etiquetas' => 'etiquetas#index', as: 'etiquetas'
  post 'etiquetas' => 'etiquetas#print', as: 'print_etiquetas'
  post 'etiquetas/:id/select'   => 'etiquetas#select',       as: 'select_etiqueta'
  post 'etiquetas/:id/unselect' => 'etiquetas#unselect',     as: 'unselect_etiqueta'
  post 'etiquetas/unselect'     => 'etiquetas#unselect_all', as: 'unselect_all_etiquetas'
  post 'etiquetas/select'       => 'etiquetas#select_page',  as: 'select_page_etiquetas'

  resources :fornecedores do
    post :arquivar, on: :member
  end

  resources :clientes do
    post :arquivar, on: :member
  end

  resources :colecoes

  resources :compras do
    resources :itens, controller: 'compras/itens'
    resources :registros, controller: 'compras/registros'
  end

  resources :sacolas do
    resources :itens, controller: 'itens_sacola' do
      post 'devolver', on: :collection
    end
    get 'print', on: :member
  end

  resources :vendas do
    resources :itens, controller: 'vendas/itens'
    resources :registros, controller: 'vendas/registros'
    get 'mensal', on: :collection
  end

  get 'financeiro/diario'
  get 'financeiro/anual'

  resources :registros do
    post :duplicate, on: :member
  end
  resources :transferencias, controller: 'registros/transferencias'

  resources :contas
  resources :categorias
  resources :formas

  get 'dashboard/index'
  root 'clientes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  include Arquivar

  has_many :vendas, dependent: :restrict_with_error

  scope :por_letra, -> (letra) { where(["nome like ?", "#{letra}%"]) }
  default_scope -> { order(:nome) }

  validates :nome, length: { maximum: 60 }, presence: true

  validate :data_aniversario

  { email:     40,
    fone_res:  20,
    fone_com:  20,
    fone_cel:  20,
    endereco:  60,
    bairro:    30,
    cep:       10,
    cidade:    60,
    uf:        2,
    obs:       100
  }.each do |key, val|
    validates key, length: { maximum: val },  allow_blank: true
  end

  def fone
    fone_cel || fone_res || fone_com
  end

  def aniversario
    unless aniver_dia.blank? || aniver_mes.blank?
      "#{aniver_dia.to_s.rjust(2, '0')}/#{aniver_mes.to_s.rjust(2, '0')}"
    end
  end

  def aniversario=(aniver)
    a = aniver.split("/")
    write_attribute(:aniver_dia, a[0])
    write_attribute(:aniver_mes, a[1])
  end


  def self.letras
    Cliente.all.map {|c| c.nome.try(:first).try(:upcase) }.uniq.sort
  end

private

  def data_aniversario
    errors.add(:aniversario, "Data Inválida") if aniver_dia.blank? != aniver_mes.blank?
    unless aniver_dia.blank? && aniver_mes.blank?
      dt = Date.new(2001, aniver_mes.to_i, aniver_dia.to_i) rescue nil
      errors.add(:aniversario, 'Data Inválida') unless dt
    end
  end

end

app/controllers/clientes_controller.rb
# coding: UTF-8
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy, :arquivar]

  def index
    params[:q] = { arquivado_eq: false } unless params[:q]

    if params[:letra]
      @search = Cliente.search(params[:q])
      @clientes = @search.result.por_letra(params[:letra]).order(:nome)
    else
      @search = Cliente.search(params[:q])
      @clientes = @search.result.order(:nome)
    end
    set_back_from(:cliente_show)
  end

  def show
    set_back_from(:venda_show)
  end

  def new
    @cliente = Cliente.new
  end

  def edit
  end

  def create
    @cliente = Cliente.new(cliente_params)

    if @cliente.save
      redirect_to @cliente, notice: 'Cliente criado com sucesso.'
    else
      render action: 'new'
    end
  end

  def update
    if @cliente.update(cliente_params)
      redirect_to @cliente, notice: 'Cliente atualizado com sucesso.'
    else
      render action: 'edit'
    end
  end

  def destroy
    if @cliente.destroy
      redirect_to clientes_path, notice: 'Cliente apagado com sucesso.'
    else
      flash[:error] = "Não foi possível apagar este cliente"
      render action: 'edit'
    end
  end

  def arquivar
    @cliente.arquivar! params[:desarquivar].blank?
    notice = params[:desarquivar].blank? ? "Arquivada" : "Desarquivada"
    redirect_to clientes_path, notice: "#{@cliente.nome} <b>#{notice}</b> com sucesso."
  end

  private

  def set_cliente
    @cliente = Cliente.find(params[:id])
  end

  def cliente_params
    params.require(:cliente)
          .permit(:nome, :email, :fone_res, :fone_com, :fone_cel, :endereco, :bairro, :cep, :cidade, :uf, :obs, :aniversario)
  end

end

app/helpers/clientes_helper.rb
module ClientesHelper

  def links_letras
    lis = Cliente.letras.map do |letra|
      active = (params[:letra] == letra) ? 'active' : ''
      tag.li class: "page-item #{active}" do
        link_to letra, clientes_path(letra: letra), class: 'page-link'
      end
    end

    tag.ul lis.join("\n").html_safe, class: 'pagination justify-content-center mb-4'
  end

end

app/views/clientes/_form.html.erb
<%= simple_form_for(@cliente) do |f| %>
  <div class="well vertical p-4 card-text">

    <div class="row">
      <div class="col-sm-5 col-md-6">
        <%= f.input :nome, label: 'Nome', input_html: { class: 'input-lg' } %>
      </div>
      <div class="col-sm-5 col-md-4">
        <%= f.input :email, label: 'email', wrapper: 'input_group', prepend: icn(:envelope) %>
      </div>
      <div class="col-sm-2 col-md-2">
        <%= f.input :aniversario, label: "Aniversário", placeholder: 'dd/mm' %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <%= f.input :fone_cel, label: 'Celular', wrapper: 'input_group', prepend: icn(:mobile_alt) %>
      </div>
      <div class="col-sm-4">
        <%= f.input :fone_res, label: 'Fone Residencial', wrapper: 'input_group', prepend: icn(:phone) %>
      </div>
      <div class="col-sm-4">
        <%= f.input :fone_com, label: 'Fone Comercial', wrapper: 'input_group', prepend: icn(:phone) %>
      </div>
      <div class="col-sm-6">
        <%= f.input :endereco, label: 'Endereco' %>
      </div>
      <div class="col-sm-4">
        <%= f.input :bairro, label: 'Bairro' %>
      </div>
      <div class="col-sm-2">
        <%= f.input :cep, label: 'CEP' %>
      </div>
      <div class="col-sm-4">
        <%= f.input :cidade, label: 'Cidade' %>
      </div>
      <div class="col-sm-2">
        <%= f.input :uf, label: 'UF' %>
      </div>
    </div>

    <div class="row">

      <div class="col-sm-12">
        <%= f.input :obs, label: 'Obs' %>
      </div>

    </div>
  </div>
  <div class="bottom-actions">
    <%= f.button :submit, 'Salvar Cliente', class: 'btn btn-primary' %>

    <% unless @cliente.new_record?  %>

      <% if @cliente.arquivado? %>
        <%= link_to icn(:arrow_circle_up_lg, 'Desarquivar este Cliente'),
            arquivar_cliente_path(@cliente, desarquivar: true),
            method: :post,
            data: { confirm: 'Tem certeza?' },
            class: 'btn btn-sm text-success ml-auto' %>
      <% else %>
        <%= link_to icn(:arrow_circle_down_lg, ' Arquivar este Cliente'),
            arquivar_cliente_path(@cliente),
            method: :post,
            data: { confirm: 'Tem certeza?' },
            class: 'btn btn-sm text-info ml-auto' %>
      <% end %>

      <%= link_to icn(:trash, 'Apagar este Cliente'),
            @cliente,
            method: :delete,
            data: { confirm: 'Tem certeza?' },
            class: 'btn btn-sm text-danger' %>

    <% end %>
  </div>

<% end %>

app/views/clientes/edit.html.erb
<%= page_header "Editar Cliente", back_to: cliente_path(@cliente) %>

<%= render 'form' %>

app/views/clientes/index.html.erb
<%= page_header "Clientes" do %>
  <%= link_to(icn(:plus, 'Novo Cliente'), new_cliente_path, class: 'btn btn-sm btn-success') %>
<% end %>

<div class="text-center affix1" data-offset-top="70"><%= links_letras %></div>

<div class="row">

  <div class="col-md-9">

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nome</th>
          <th>email</th>
          <th class="right">Fone</th>
          <th class="right">Aniver</th>
          <th class="right">Vendas</th>
        </tr>
      </thead>
      <tbody>
        <% @clientes.each do |cliente| %>
          <tr>
            <td><%= link_to cliente.nome, cliente %></td>
            <td><%= cliente.email %></td>
            <td class="right"><%= cliente.fone %></td>
            <td class="right"><%= cliente.aniversario %></td>
            <td class="right"><%= label_estoque(cliente.vendas.count) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <hr>
    <%= index_count @clientes.count, "clientes encontradas" %>

  </div>

  <div class="col-md-3">

    <div class="card">
      <div class="card-header">
        <b>Filtros</b>
      </div>
      <div class="card-body card-text">
        <%= simple_form_for @search, url: clientes_path, method: 'GET' do |f| %>
          <%= f.input :nome_cont, label: "Nome" %>
          <%= f.input :arquivado_eq, label: "Exibir Arquivados", as: :boolean %>

          <hr>
          <%= f.submit 'Filtrar', class: 'btn btn-info btn-sm' %>
          <%= button_tag 'Limpar', class: 'btn btn-light btn-sm clear' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/clientes/new.html.erb
<%= page_header "Novo Cliente", back_to: clientes_path %>

<%= render 'form' %>

app/views/clientes/show.html.erb
<%= page_header "Exibir Cliente" do %>
  <%= link_to_back get_back_for(:cliente_show) %>

<% end %>

<div class="well vertical p-3 card-text mb-4">

    <h4 class="text-primary">
      <%= @cliente.nome %>
    </h4>

    <div class="row">

      <div class="col-3">
        <label>Email</label>
        <p><%= @cliente.email %></p>
      </div>
      <div class="col-3">
        <label>Celular</label>
        <p><%= @cliente.fone_cel %></p>
      </div>

    </div>

    <%= link_to icn(:edit, 'Editar Cliente'), edit_cliente_path(@cliente), class: 'action' %>

</div>

<div class="well p-3">
  <table class="table table-sm mb-0">
    <tbody>
      <% @cliente.vendas.includes(itens: { item: [:produto, :cor, :tamanho] }).order(data: :desc).each do |venda| %>
        <tr class='header'>
          <td colspan="10"> <%= venda.data %> &nbsp;&nbsp;&nbsp; <%= link_to venda.descr, venda %>   </td>
        </tr>
        <% venda.itens.each do |item| %>
        <tr>
          <td><%= item.produto.ref %></td>
          <td><%= item.produto.tipo.descricao %></td>
          <td><%= item.produto.fornecedor.nome %></td>
          <td><%= item.tamanho.try :nome %></td>
          <td><%= item.cor.try :nome %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

</div>