config/routes.rb
Rails.application.routes.draw do

  resources :tipos
  resources :linhas
  resources :tamanhos
  resources :cores

  resources :produtos do
    get :lucro, on: :collection
    resources :etiquetas
  end

  resources :vendas do
    resources :itens, controller: 'vendas/itens'
    resources :trocas, controller: 'vendas/trocas'
    resources :registros, controller: 'vendas/registros'
    get 'mensal', on: :collection
  end

  resources :compras do
    resources :itens, controller: 'compras/itens'
    resources :registros, controller: 'compras/registros'
    resources :trocas, controller: 'compras/trocas'
  end

  resources :ajustes do
    resources :itens, controller: 'ajustes/itens'
  end

  resources :estoque

  get  'etiquetas' => 'etiquetas#index', as: 'etiquetas'
  post 'etiquetas' => 'etiquetas#print', as: 'print_etiquetas'
  post 'etiquetas/:id/select'   => 'etiquetas#select',       as: 'select_etiqueta'
  post 'etiquetas/:id/unselect' => 'etiquetas#unselect',     as: 'unselect_etiqueta'
  post 'etiquetas/unselect'     => 'etiquetas#unselect_all', as: 'unselect_all_etiquetas'
  post 'etiquetas/select'       => 'etiquetas#select_page',  as: 'select_page_etiquetas'

  resources :fornecedores do
    post :arquivar, on: :member
  end

  resources :clientes do
    post :arquivar, on: :member
  end

  resources :colecoes

  resources :compras do
    resources :itens, controller: 'compras/itens'
    resources :registros, controller: 'compras/registros'
  end

  resources :sacolas do
    resources :itens, controller: 'itens_sacola' do
      post 'devolver', on: :collection
    end
    get 'print', on: :member
  end

  resources :vendas do
    resources :itens, controller: 'vendas/itens'
    resources :registros, controller: 'vendas/registros'
    get 'mensal', on: :collection
  end

  get 'financeiro/diario'
  get 'financeiro/anual'

  resources :registros do
    post :duplicate, on: :member
  end
  resources :transferencias, controller: 'registros/transferencias'

  resources :contas
  resources :categorias
  resources :formas

  get 'dashboard/index'
  root 'clientes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conta.rb
class Conta < ActiveRecord::Base

  validates_length_of :nome, maximum: 20

  has_many :registros

  def self.to_select
    Conta.order(:nome).pluck(:nome, :id)
  end

  def saldo
    registros.creditos.pagos.sum(:valor) - registros.debitos.pagos.sum(:valor)
  end

end

app/controllers/contas_controller.rb
class ContasController < ApplicationController
  before_action :set_conta, only: [:show, :edit, :update, :destroy]

  def index
    @contas = Conta.order(:nome)
  end

  def new
    @conta = Conta.new
  end

  def edit
  end

  def create
    @conta = Conta.new(conta_params)

    if @conta.save
      redirect_to contas_path, notice: 'Conta criada com sucesso.'
    else
      render action: 'new'
    end
  end

  def update
    if @conta.update(conta_params)
      redirect_to contas_path, notice: 'Conta atualizada com sucesso.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @conta.destroy
    redirect_to contas_path, notice: 'Conta apagada com sucesso.'
  end

  private
    def set_conta
      @conta = Conta.find(params[:id])
    end

    def conta_params
      params.require(:conta).permit(:nome)
    end
end

app/views/contas/_form.html.erb
<%= simple_form_for(@conta) do |f| %>

  <div class="row">
    <div class="col-md-6">

      <%= f.input :nome, label: 'Nome' %>
    </div>
  </div>

  <div class="bottom-actions">
    <%= f.button :submit, 'Salvar Conta', class: 'btn btn-primary' %>

    <%= link_to icn(:trash, 'Apagar este Conta'),
          @conta,
          method: :delete,
          data: { confirm: 'Tem certeza?' },
          class: 'btn btn-sm text-danger ml-auto' unless @conta.new_record? %>
  </div>

<% end %>

app/views/contas/edit.html.erb
<%= page_header "Editar Conta", back_to: contas_path %>

<%= render 'form' %>

app/views/contas/index.html.erb
<%= page_header "Contas" do %>
  <%= link_to(icn(:plus, 'Nova Conta'), new_conta_path, class: 'btn btn-sm btn-success') %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
    </tr>
  </thead>
  <tbody>
    <% @contas.each do |conta| %>
      <tr>
        <td><%= link_to conta.nome, edit_conta_path(conta) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr/>
<%= index_count(@contas.count, 'contas encontradas') %>

app/views/contas/new.html.erb
<%= page_header "Nova Conta", back_to: contas_path %>

<%= render 'form' %>