config/routes.rb
Rails.application.routes.draw do

  resources :tipos
  resources :linhas
  resources :tamanhos
  resources :cores

  resources :produtos do
    get :lucro, on: :collection
    resources :etiquetas
  end

  resources :vendas do
    resources :itens, controller: 'vendas/itens'
    resources :trocas, controller: 'vendas/trocas'
    resources :registros, controller: 'vendas/registros'
    get 'mensal', on: :collection
  end

  resources :compras do
    resources :itens, controller: 'compras/itens'
    resources :registros, controller: 'compras/registros'
    resources :trocas, controller: 'compras/trocas'
  end

  resources :ajustes do
    resources :itens, controller: 'ajustes/itens'
  end

  resources :estoque

  get  'etiquetas' => 'etiquetas#index', as: 'etiquetas'
  post 'etiquetas' => 'etiquetas#print', as: 'print_etiquetas'
  post 'etiquetas/:id/select'   => 'etiquetas#select',       as: 'select_etiqueta'
  post 'etiquetas/:id/unselect' => 'etiquetas#unselect',     as: 'unselect_etiqueta'
  post 'etiquetas/unselect'     => 'etiquetas#unselect_all', as: 'unselect_all_etiquetas'
  post 'etiquetas/select'       => 'etiquetas#select_page',  as: 'select_page_etiquetas'

  resources :fornecedores do
    post :arquivar, on: :member
  end

  resources :clientes do
    post :arquivar, on: :member
  end

  resources :colecoes

  resources :compras do
    resources :itens, controller: 'compras/itens'
    resources :registros, controller: 'compras/registros'
  end

  resources :sacolas do
    resources :itens, controller: 'itens_sacola' do
      post 'devolver', on: :collection
    end
    get 'print', on: :member
  end

  resources :vendas do
    resources :itens, controller: 'vendas/itens'
    resources :registros, controller: 'vendas/registros'
    get 'mensal', on: :collection
  end

  get 'financeiro/diario'
  get 'financeiro/anual'

  resources :registros do
    post :duplicate, on: :member
  end
  resources :transferencias, controller: 'registros/transferencias'

  resources :contas
  resources :categorias
  resources :formas

  get 'dashboard/index'
  root 'clientes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/financeiro_controller.rb
class FinanceiroController < ApplicationController

  def diario
    @diario = Diario.new(params[:mes])
  end

  def anual
    @anual = Anual.new(params[:ano])
  end

end

app/views/financeiro/anual.html.erb
<%= page_header "Financeiro Anual" %>



<div class="well well-row center mb-4 h2">
  <%= link_to icn(:arrow_left), financeiro_anual_path(ano: @anual.calendar.last_year), class: "mr-3" %>
  <%= @anual.calendar.year %>
  <%= link_to icn(:arrow_right), financeiro_anual_path(ano: @anual.calendar.next_year), class: "ml-3" %>
</div>

<%= line_chart @anual.saldos,
                  label: "Saldo",
                  library: {
                    plotOptions: {
                      series: {
                        dataLabels: { enabled: true }
                      }
                    }
                  }
 %>
<hr>
<h4 class="mt-5 mb-3">Receitas e Despesas - Totais do Ano </h4>

<div class="well flex-column stats mb-4 px-4">
  <div class="row">
    <div class="col-3 text-muted">
      <h1> <%= number_to_currency @anual.saldo_inicial %></h1>
      <small>SALDO ANTERIOR</small>
    </div>
    <div class="col-3 text-danger">
      <h1> <%= number_to_currency @anual.total_despesas %></h1>
      <small>TOTAL DE DESPESAS</small>
    </div>
    <div class="col-3 text-success">
      <h1> <%= number_to_currency @anual.total_receitas %></h1>
      <small>TOTAL DE RECEITAS</small>
    </div>
    <div class="col-3 text-primary">
      <h1> <%= number_to_currency @anual.saldo_final %></h1>
      <small>SALDO FINAL</small>
    </div>
  </div>
</div>

 <div class="row">

   <div class="col-sm-12 col-md-6">

     <div class="card">
       <div class="card-header alert-danger">
         <b>DESPESAS</b>
       </div>
       <table class="table table-striped mb-0">
         <tbody>
           <% @anual.despesas.each do |cat, valor| %>
           <tr>
             <td><%= cat.try(:nome) || 'SEM CATEGORIA' %></td>
             <td class='text-right' ><%= number_to_currency(valor) %></td>
           </tr>
           <% end %>
         </tbody>
       </table>
     </div>

   </div>

   <div class="col-sm-12 col-md-6">

     <div class="card">
       <div class="card-header alert-success">
         <b>RECEITAS</b>
       </div>
       <table class="table table-striped mb-0">
         <tbody>
           <% @anual.receitas.each do |cat, valor| %>
           <tr>
             <td><%= cat.try(:nome) || 'SEM CATEGORIA' %></td>
             <td class='text-right' ><%= number_to_currency(valor) %></td>
           </tr>
           <% end %>
         </tbody>
       </table>
     </div>

   </div>

app/views/financeiro/diario.html.erb
<%= page_header "Diário Financeiro" do %>

  <%= link_to icn(:exchange_alt, 'Transferência'), new_transferencia_path, class: 'btn btn-sm btn-info', data: { behavior: 'load-modal'} %>
  <%= link_to icn(:plus, 'Incluir Receita'), new_registro_path(cd: 'C'), class: 'btn btn-sm btn-success ml-4', data: { behavior: 'load-modal'} %>
  <%= link_to icn(:minus, 'Incluir Despesa'), new_registro_path(cd: 'D'), class: 'btn btn-sm btn-danger ml-1', data: { behavior: 'load-modal'} %>

<% end %>

<%= render 'financeiro/diario/nav' %>

<div class="row">

  <% if @diario.calendar.future? %>
    <%= render partial: 'financeiro/diario/conta_futuro', collection: @diario.contas, as: :conta %>
  <% else %>
    <%= render partial: 'financeiro/diario/conta', collection: @diario.contas %>
  <% end %>

</div>

<div class="well well-row mb-4">
  <%= link_to icn(:minus, 'Incluir Despesa'), new_registro_path(cd: 'D'), class: 'btn btn-sm btn-danger', data: { behavior: 'load-modal'} %>
  <%= link_to icn(:plus, 'Incluir Receita'), new_registro_path(cd: 'C'), class: 'btn btn-sm btn-success ml-2', data: { behavior: 'load-modal'} %>

  <%= link_to icn(:exchange_alt, 'Transferência'), new_transferencia_path, class: 'btn btn-sm btn-info ml-auto', data: { behavior: 'load-modal'} %>
</div>

<% unless @diario.calendar.future? %>
<hr/>
<div class="row">

  <div class="col-sm-12 col-md-5">
    <%= render partial: 'financeiro/diario/cpagar' %>
  </div>

  <div class="col-sm-12 col-md-7">
    <%= render partial: 'financeiro/diario/creceber' %>
  </div>

</div>
<% end %>

<hr/>
<br/>

<h3>Saldo Total por Dia</h3><br/>
<%= line_chart @diario.saldos,
                label: "Saldo",
                library: {
                  plotOptions: {
                    series: {
                      dataLabels: { enabled: false },
                      negativeColor: 'red' } } } %>

<%= render 'financeiro/diario/nav' %>

<h4>Receitas e Despesas - Totais do Mês </h4>

<%= render partial: 'financeiro/diario/totais_rd' %>

<div class="row">

  <div class="col-sm-12 col-md-6">
    <%= render partial: 'financeiro/diario/despesas' %>
  </div>

  <div class="col-sm-12 col-md-6">
    <%= render partial: 'financeiro/diario/receitas' %>
  </div>

</div>